# Generated by Django 5.1.2 on 2024-10-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_remove_booking_user_booking_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Client',
            new_name='client',
        ),
    ]
