# Generated by Django 5.1.2 on 2024-10-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_booking_user'),
        ('users', '0002_client_alter_child_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.section')),
            ],
            options={
                'unique_together': {('client', 'section')},
            },
        ),
    ]
