# Generated by Django 5.1.2 on 2024-11-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_booking_child_alter_booking_status'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='merchant.partner'),
        ),
    ]
