# Generated by Django 5.1.2 on 2024-10-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_text', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('total_days', models.PositiveIntegerField()),
                ('freeze_days', models.PositiveIntegerField()),
                ('daily_visits', models.PositiveIntegerField()),
                ('monthly_visits', models.PositiveIntegerField()),
                ('premium_monthly_visits', models.PositiveIntegerField()),
            ],
        ),
    ]
