# Generated by Django 5.1.2 on 2024-10-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_visits',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
