# Generated by Django 5.1.2 on 2024-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersubscription_daily_visits_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_visits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='used_visits',
            field=models.PositiveIntegerField(),
        ),
    ]
