# Generated by Django 5.1.2 on 2024-11-01 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersubscription_remaining_freeze_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='freeze_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_visits',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='used_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
