# Generated by Django 5.1.2 on 2024-11-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersubscription_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='freeze_days',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_days',
            field=models.PositiveIntegerField(),
        ),
    ]
