# Generated by Django 5.1.2 on 2024-11-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersubscription_daily_visits_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
