# Generated by Django 5.1.2 on 2024-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersubscription_daily_visits_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='daily_visits_limit',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
