# Generated by Django 5.1.2 on 2024-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usersubscription_daily_visits_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='total_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
