# Generated by Django 5.1.3 on 2024-11-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_agegroup_alter_subscription_age_group'),
        ('users', '0012_alter_usersubscription_total_days'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('used_visits__lte', models.F('total_visits'))), name='used_visits_lte_total_visits'),
        ),
    ]
